config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter-opener" if Rails.env.development?

  namespace :admin, path: "/admin" do
    root to: redirect("/admin/schulungen")

    resources :training_courses, path: "schulungen" do
      get :preview_reminder_message, path: "preview-reminder-message", on: :member
      get :export, on: :collection
      patch :batch_update, path: "batch-update", on: :collection

      resources :registrations do
        get :download_certificate, on: :member, path: "zertifikat/download"
        get :email_certificate, on: :member, path: "zertifikat/email"
        patch :batch_update, path: "batch-update", on: :collection
      end
      resources :repetitions, only: [:new, :create]
    end

    resources :categories, path: "themen" do
      patch :reorder, on: :collection
    end

    resources :target_audiences, path: "zielgruppen" do
      patch :reorder, on: :collection
    end

    resources :institutions, path: "einrichtungen" do
      patch :reorder, on: :collection
    end
  end

  namespace :frontend, path: "/" do
    get "datenschutz", as: :privacy, to: redirect("https://www.ub.uni-paderborn.de/fileadmin/ub/Dokumente_Formulare/DSE_UB_001_Schulungsdatenbank.pdf")
    get "impressum", as: :legal, to: redirect("https://www.ub.uni-paderborn.de/ueber-uns/impressum/")

    resources :cert_checks, path: "validate", only: [:index, :new, :create, :show]

    resources :training_courses, path: "/", only: [:index, :show] do
      resources :registrations, only: [:new, :create]
    end
  end
end

app/models/institution.rb
class Institution < ApplicationRecord

  # Relations
  has_and_belongs_to_many :registrations

  # Validations
  validates :title, presence: true, uniqueness: true

  # List support
  acts_as_list

end

app/controllers/admin/institutions_controller.rb
class Admin::InstitutionsController < Admin::ApplicationController

  def index
    @institutions = Institution.order("position")
  end

  def new
    @institution = Institution.new
  end

  def create
    @institution = Institution.new(institution_params)

    if @institution.save
      @institution.move_to_bottom
      flash[:success] = t(".flash.success")
      redirect_to(admin_institutions_path)
    else
      render :new
    end
  end

  def edit
    @institution = Institution.find(params[:id])
  end

  def update
    @institution = Institution.find(params[:id])

    if @institution.update(institution_params)
      flash[:success] = t(".flash.success")
      redirect_to(admin_institutions_path)
    else
      render :edit
    end
  end

  def destroy
    @institution = Institution.find(params[:id])

    if @institution.destroy
      flash[:success] = t(".flash.success")
    else
      flash[:error] = t(".flash.error")
    end

    redirect_to(admin_institutions_path)
  end

  def reorder
    institutions = Institution.find(params[:new_order])

    institutions.each.with_index(1) do |institution, index|
      institution.update_column :position, index
    end

    head :ok
  end

private

  def institution_params
    params.require(:institution).permit(:title)
  end

end

app/views/admin/institutions/_form_fields.html.slim
= form.input :title

app/views/admin/institutions/_listing.html.slim
ul#sortable.list-group.list-group-flush(data-reorder-url=reorder_admin_institutions_path)
  - institutions.each do |i|
    li.list-group-item(data-sort-id=i.id)
      .d-flex.w-100.justify-content-between.align-items-center
        div
          = icon("fas", "bars", class: "fa-lg sort-handle")
          strong =< i.title
        .btn-toolbar.justify-content-end.flex-nowrap
          div
            = link_to edit_admin_institution_path(i), class: "btn btn-outline-primary" do
              = icon("fas", "pencil-alt")

= render "admin/application/sortable", element: "sortable"

app/views/admin/institutions/edit.html.slim
.container-fluid
  .row.justify-content-center
    .col-md-8
      .card
        h5.card-header = t(".header")
        = simple_form_for [:admin, @institution] do |f|
          .card-body
            = render "form_fields", form: f
          .card-footer
            .btn-toolbar.justify-content-between.flex-nowrap
              div
                = f.submit t("admin.application.btn_save"), class: "btn btn-primary"
                =< link_to t("admin.application.btn_cancel"), admin_institutions_path, class: "btn btn-secondary"
              div
                = link_to t("admin.application.btn_delete"), admin_institution_path(@institution), method: :delete, data: {confirm: t("admin.application.confirm_delete")}, class: "btn btn-danger"

app/views/admin/institutions/index.html.slim
.container-fluid
  .row.justify-content-center
    .col-md-8
      .card
        h5.card-header = t(".header")
        - if @institutions.present?
          = render "listing", institutions: @institutions
        - else
          .card-body
            .alert.alert-info.mb-0 = t(".no_institutions")
        .card-footer
          .btn-toolbar.justify-content-start
            = link_to new_admin_institution_path, class: "btn btn-primary" do
              = icon("fas", "plus")
              =< t(".new_institution")

app/views/admin/institutions/new.html.slim
.container-fluid
  .row.justify-content-center
    .col-md-8
      .card
        h5.card-header = t(".header")
        = simple_form_for [:admin, @institution] do |f|
          .card-body
            = render "form_fields", form: f
          .card-footer
            = f.submit t("admin.application.btn_save"), class: "btn btn-primary"
            =< link_to t("admin.application.btn_cancel"), admin_institutions_path, class: "btn btn-secondary"