config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter-opener" if Rails.env.development?

  namespace :admin, path: "/admin" do
    root to: redirect("/admin/schulungen")

    resources :training_courses, path: "schulungen" do
      get :preview_reminder_message, path: "preview-reminder-message", on: :member
      get :export, on: :collection
      patch :batch_update, path: "batch-update", on: :collection

      resources :registrations do
        get :download_certificate, on: :member, path: "zertifikat/download"
        get :email_certificate, on: :member, path: "zertifikat/email"
        patch :batch_update, path: "batch-update", on: :collection
      end
      resources :repetitions, only: [:new, :create]
    end

    resources :categories, path: "themen" do
      patch :reorder, on: :collection
    end

    resources :target_audiences, path: "zielgruppen" do
      patch :reorder, on: :collection
    end

    resources :institutions, path: "einrichtungen" do
      patch :reorder, on: :collection
    end
  end

  namespace :frontend, path: "/" do
    get "datenschutz", as: :privacy, to: redirect("https://www.ub.uni-paderborn.de/fileadmin/ub/Dokumente_Formulare/DSE_UB_001_Schulungsdatenbank.pdf")
    get "impressum", as: :legal, to: redirect("https://www.ub.uni-paderborn.de/ueber-uns/impressum/")

    resources :cert_checks, path: "validate", only: [:index, :new, :create, :show]

    resources :training_courses, path: "/", only: [:index, :show] do
      resources :registrations, only: [:new, :create]
    end
  end
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController

  layout "admin/application"

  before_action :authenticate!

private

  def authenticate!
    authenticate_or_request_with_http_basic do |username, password|
      # Create the hash with BCrypt::Password.create("mypassword")
      secure_password = BCrypt::Password.new("$2a$10$tIn1TbsFf7N91sKIMyM/qegksPWejFInWBHwdtJ1xQvMOAT.PiFvy")
      username == "admin" && secure_password == password
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/frontend/application_controller.rb
class Frontend::ApplicationController < ApplicationController

  layout "frontend/application"

private

  def add_breadcrumb(label, url)
    (@breadcrumbs ||= []) << {label: label, url: url}
  end

  def breadcrumbs
    @breadcrumbs || []
  end
  helper_method :breadcrumbs

  def set_page_title(title)
    @page_title = title
  end

  def page_title
    @page_title
  end
  helper_method :page_title

end

app/helpers/application_helper.rb
module ApplicationHelper

  def active_when(path)
    if path.is_a?(Regexp)
      request.fullpath =~ path ? "active" : "inactive"
    elsif path == true
      "active"
    elsif path == false
      "inactive"
    else
      current_page?(path) ? "active" : "inactive"
    end
  end

  def render_markdown(s)
    Commonmarker.to_html(s, options: {
      parse: { smart: true },
      render: { hardbreaks: false }
    })
  end

  def date_in_words(date)
    case date
    when Date.today          then t("datetime.today")
    when Date.today + 1.day  then t("datetime.tomorrow")
    when Date.today + 2.days then t("datetime.day_after_tomorrow")
    else distance_of_time_in_words_to_now(date, scope: "datetime.distance_in_words.date_only")
    end
  end

end

app/views/admin/application/_main_nav.html.slim
nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  .container-fluid
    a.navbar-brand(href="/admin")
      = icon("fas", "database")
      =< t(".app_title")

    button.navbar-toggler(type="button" data-toggle="collapse" data-target="#navbarContent")
      span.navbar-toggler-icon

    #navbarContent.collapse.navbar-collapse
      ul.navbar-nav.me-auto
        li.nav-item(class=active_when(/schulungen/))
          = link_to t(".training_courses"), admin_training_courses_path, class: "nav-link"
        li.nav-item(class=active_when(/themen/))
          = link_to t(".categories"), admin_categories_path, class: "nav-link"
        li.nav-item(class=active_when(/zielgruppen/))
          = link_to t(".target_audiences"), admin_target_audiences_path, class: "nav-link"
        li.nav-item(class=active_when(/einrichtungen/))
          = link_to t(".institutions"), admin_institutions_path, class: "nav-link"

app/views/admin/application/_sortable.html.slim
javascript:
  var el = document.getElementById("#{element}");
  var sortable = Sortable.create(el, {
    handle: ".sort-handle",
    onUpdate: function(e) {
      var sortResult = $(e.to).find("li").map(function() {
        return $(this).data("sort-id")
      }).get();

      $.ajax({
        url: $(e.to).data("reorder-url"),
        data: {new_order: sortResult},
        method: "PATCH"
      });
    }
  });