config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter-opener" if Rails.env.development?

  namespace :admin, path: "/admin" do
    root to: redirect("/admin/schulungen")

    resources :training_courses, path: "schulungen" do
      get :preview_reminder_message, path: "preview-reminder-message", on: :member
      get :export, on: :collection
      patch :batch_update, path: "batch-update", on: :collection

      resources :registrations do
        get :download_certificate, on: :member, path: "zertifikat/download"
        get :email_certificate, on: :member, path: "zertifikat/email"
        patch :batch_update, path: "batch-update", on: :collection
      end
      resources :repetitions, only: [:new, :create]
    end

    resources :categories, path: "themen" do
      patch :reorder, on: :collection
    end

    resources :target_audiences, path: "zielgruppen" do
      patch :reorder, on: :collection
    end

    resources :institutions, path: "einrichtungen" do
      patch :reorder, on: :collection
    end
  end

  namespace :frontend, path: "/" do
    get "datenschutz", as: :privacy, to: redirect("https://www.ub.uni-paderborn.de/fileadmin/ub/Dokumente_Formulare/DSE_UB_001_Schulungsdatenbank.pdf")
    get "impressum", as: :legal, to: redirect("https://www.ub.uni-paderborn.de/ueber-uns/impressum/")

    resources :cert_checks, path: "validate", only: [:index, :new, :create, :show]

    resources :training_courses, path: "/", only: [:index, :show] do
      resources :registrations, only: [:new, :create]
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord

  # Relations
  has_and_belongs_to_many :training_courses

  # Validations
  validates :title, presence: true, uniqueness: true

  # List support
  acts_as_list

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController

  def index
    @categories = Category.order("position")
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      @category.move_to_bottom
      flash[:success] = t(".flash.success")
      redirect_to(admin_categories_path)
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      flash[:success] = t(".flash.success")
      redirect_to(admin_categories_path)
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])

    if @category.destroy
      flash[:success] = t(".flash.success")
    else
      flash[:error] = t(".flash.error")
    end

    redirect_to(admin_categories_path)
  end

  def reorder
    categories = Category.find(params[:new_order])

    categories.each.with_index(1) do |category, index|
      category.update_column :position, index
    end

    head :ok
  end

private

  def category_params
    params.require(:category).permit(:title)
  end

end

app/views/admin/categories/_listing.html.slim
ul#sortable.list-group.list-group-flush(data-reorder-url=reorder_admin_categories_path)
  - categories.each do |c|
    li.list-group-item(data-sort-id=c.id)
      .d-flex.w-100.justify-content-between.align-items-center
        div
          = icon("fas", "bars", class: "fa-lg sort-handle")
          strong =< c.title
        .btn-toolbar.justify-content-end.flex-nowrap
          div
            = link_to edit_admin_category_path(c), class: "btn btn-outline-primary" do
              = icon("fas", "pencil-alt")

= render "admin/application/sortable", element: "sortable"

app/views/admin/categories/edit.html.slim
.container-fluid
  .row.justify-content-center
    .col-md-8
      .card
        h5.card-header = t(".header")
        = simple_form_for [:admin, @category] do |f|
          .card-body
            = render "form_fields", form: f
          .card-footer
            .btn-toolbar.justify-content-between.flex-nowrap
              div
                = f.submit t("admin.application.btn_save"), class: "btn btn-primary"
                =< link_to t("admin.application.btn_cancel"), admin_categories_path, class: "btn btn-secondary"
              div
                = link_to t("admin.application.btn_delete"), admin_category_path(@category), method: :delete, data: {confirm: t("admin.application.confirm_delete")}, class: "btn btn-danger"

app/views/admin/categories/index.html.slim
.container-fluid
  .row.justify-content-center
    .col-md-8
      .card
        h5.card-header = t(".header")
        - if @categories.present?
          = render "listing", categories: @categories
        - else
          .card-body
            .alert.alert-info.mb-0 = t(".no_categories")
        .card-footer
          .btn-toolbar.justify-content-start
            = link_to new_admin_category_path, class: "btn btn-primary" do
              = icon("fas", "plus")
              =< t(".new_category")

app/views/admin/categories/new.html.slim
.container-fluid
  .row.justify-content-center
    .col-md-8
      .card
        h5.card-header = t(".header")
        = simple_form_for [:admin, @category] do |f|
          .card-body
            = render "form_fields", form: f
          .card-footer
            = f.submit t("admin.application.btn_save"), class: "btn btn-primary"
            =< link_to t("admin.application.btn_cancel"), admin_categories_path, class: "btn btn-secondary"